function generate() {
    const header = [
        "// Generated by Project Rizz Script Gen",
        "// Website made by Unixityyy",
        "// https://unixityyy.github.io/pjrz-script-generator/",
        ""
    ];

    let declarations = [];
    let body = [];

    if (document.getElementById('lavaMat').checked) declarations.push("let matSet = false;");
    if (document.getElementById('noVibration').checked || document.getElementById('maxVibration').checked) declarations.push("let intensitySet = false;");

    if (document.getElementById('rGripSpeed').checked) {
        body.push(
            "    if (RightController.GripValue >= 0.5) {",
            "        PlayerSettings.JumpMultiplier = 2.5;",
            "        PlayerSettings.MaxJumpSpeed = 7.5;",
            "    } else {",
            "        PlayerSettings.JumpMultiplier = 1.5;",
            "        PlayerSettings.MaxJumpSpeed = 6.5;",
            "    }\n"
        );
    }

    if (document.getElementById('lGripSpeed').checked) {
        body.push(
            "    if (LeftController.GripValue >= 0.5) {",
            "        PlayerSettings.JumpMultiplier = 2.5;",
            "        PlayerSettings.MaxJumpSpeed = 7.5;",
            "    } else {",
            "        PlayerSettings.JumpMultiplier = 1.5;",
            "        PlayerSettings.MaxJumpSpeed = 6.5;",
            "    }\n"
        );
    }

    if (document.getElementById('lavaMat').checked) {
        body.push(
            "    if (!matSet) {",
            "        matSet = true;",
            "        LocalPlayer.Material = 1;",
            "    }"
        );
    }

    if (document.getElementById('noVibration').checked) {
        body.push(
            "    if (!intensitySet) {",
            "        intensitySet = true;",
            "        PlayerSettings.VibrateIntensity = 0;",
            "    }"
        );
    }

    if (document.getElementById('maxVibration').checked) {
        body.push(
            "    if (!intensitySet) {",
            "        intensitySet = true;",
            "        PlayerSettings.VibrateIntensity = 1;",
            "    }"
        );
    }

    const fullScript = [
        ...header,
        ...declarations,
        (declarations.length > 0 ? "" : null),
        "function tick(dt) {",
        ...body,
        "}"
    ].filter(line => line !== null).join("\n");

    document.getElementById('output').value = fullScript;
}
